---

- name: Copy utility
  template:
    src: crontask-rebuild-file-cache.sh.j2
    dest: dest: "{{ hp_home_dir }}/crontask-rebuild-file-cache.sh"
    mode: '0755'

- name: Copy services
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system/{{ item | basename | regex_replace('\.j2$', '') }}
    owner: root
    group: root
    mode: '0664'
  loop:
    - rebuild-file-cache.service.j2
    - rebuild-file-cache.timer.j2
  notify:
    - restart rebuild file cache timer
