---
- name: Install necessary dependencies
  dnf:
    name:
      - curl
      - git
      - python3
    state: present

- name: Ensure hashiproxy user
  user:
    name: "{{ hp_user }}"
    home: "{{ hp_home_dir }}"
    shell: "/bin/bash"
    system: True
    state: "present"

- name: Checkout fileserver source from git repo
  become_user: "{{ hp_user }}"
  ansible.builtin.git:
    repo: "{{ hp_fs_repo }}"
    dest: "{{ hp_fs_install_dir }}"
    force: True

- name: Ensure fileserver.py permissions
  become_user: "{{ hp_user }}"
  file:
    path: "{{ hp_fs_install_dir }}/fileserver.py"
    mode: "0755"
    state: file

- name: Update config.yaml
  become_user: "{{ hp_user }}"
  template:
    src: fileserver-config.yaml.j2
    dest: "{{ hp_fs_install_dir }}/config.yaml"
    mode: '0644'

- name: Ensure files directory
  become_user: "{{ hp_user }}"
  file:
    path: "{{ hp_fs_mirror_dir }}"
    mode: "0755"
    state: directory

- name: Copy service
  template:
    src: hashicorp-proxy.service.j2
    dest: /etc/systemd/system/hashicorp-proxy.service
    owner: root
    group: root
    mode: '0664'
  notify:
    - restart hashicorp-proxy service

- name: Add firewalld rule if needed
  ansible.posix.firewalld:
    port: "{{ hp_fs_port }}/tcp"
    permanent: true
    state: enabled
  notify: reload firewalld
  when: hp_add_open_ext_port
