---
- name: Setup fileserver
  include_tasks: fileserver.yml
  args:
    apply:
      become: True
  tags:
    - fileserver

- name: Rebuild file cache
  include_tasks: cache.yml
  args:
    apply:
      become: True
  tags:
    - cache

- name: Force all notified handlers to run at this point
  meta: flush_handlers