---
- name: Setup fileserver
  include_tasks: fileserver.yml
  args:
    apply:
      become: True
  tags:
    - fileserver

- name: Rebuild file cache
  include_tasks: cache.yml
  args:
    apply:
      become: True
  tags:
    - cache