---
- name: Ensure firewalld service reloaded
  systemd:
    name: firewalld
    state: reloaded
  listen: reload firewalld

- name: Ensure rebuild file cache timer restarted
  systemd:
    name: rebuild-file-cache.timer
    state: restarted
    enabled: true
    daemon_reload: True
  listen: restart rebuild file cache timer

- name: Ensure rebuild file cache service restarted
  systemd:
    name: rebuild-file-cache.service
    state: restarted
    enabled: false
    daemon_reload: True
  listen: restart rebuild file cache service

- name: Ensure hashicorp-proxy service restarted
  systemd:
    name: hashicorp-proxy.service
    state: restarted
    enabled: true
    daemon_reload: True
  listen: restart hashicorp-proxy service